#pragma once
#include <string>
#include <vector>
#include <iostream>
#include <cstring>
#include <cstdint>
#include <climits>
#include <atomic>
#include <functional>
#include <mutex>
#define NOMINMAX
#include <limits>
#include <thread>
